// Action Types

// Authors
export const LIST_REQUEST = 'AUTHORS/LIST/REQUEST';
export const LIST_RESPONSE = 'AUTHORS/LIST/RESPONSE';
export const LIST_DONE = 'AUTHORS/LIST/DONE';

// Search

export const AUTHORS_UPDATE_SEARCH = 'AUTHORS/UPDATE/SEARCH';
export const POSTS_UPDATE_SEARCH = 'POSTS/UPDATE/SEARCH';

export const SET_POST_LIST = 'SET_POST_LIST';
